use std::{collections::HashMap, fs, path::PathBuf, time::Instant};

use anyhow::{Result, bail};
use clap::Parser;
use object::{Object, read::pe::PeFile64};
use pdb_wrapper::{
    PDB, PDBFunction, PDBType, StructField,
    pdb_meta::{CallingConvention, SimpleTypeKind},
};
use regex::Regex;
use serde::{Deserialize, Deserializer};

#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct PdbArgs {
    #[arg(
        short,
        long,
        default_value = "il2cpp_dump.json",
        help = "path to il2cpp dump generated by reframework"
    )]
    il2cpp: String,
    #[arg(
        short,
        long,
        help = "path to the game exe, e.g 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\MonsterHunterWilds\\MonsterHunterWilds.exe'"
    )]
    exe: String,
    #[arg(
        short,
        long,
        help = "path to the output directory, e.g 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\MonsterHunterWilds'. If unspecified, it will be written to the directory of the exe"
    )]
    output: Option<String>,
    #[arg(
        short,
        long,
        help = "name of the pdb file (file will be written as \"<name>.pdb\", default uses the name of the exe)"
    )]
    name: Option<String>,
    #[arg(
        short,
        long,
        help = "override for the age that will be written to the pdb file"
    )]
    age: Option<u32>,
    #[arg(
        short,
        long,
        help = "override for the signature that will be written to the pdb file (default=0)"
    )]
    signature: Option<u32>,
    #[arg(
        short,
        long,
        help = "override for the guid that will be written to the pdb file"
    )]
    guid: Option<String>,
    #[arg(short, long, help = "regex filter for types to add")]
    filter: Option<String>,
    #[arg(short, long)]
    verbose: bool,
    #[arg(
        long,
        // it doesn't work with 0x140000000 and 0th segment, I'm probably just dumb though
        default_value_t = 0x140001000,
        help = "base address of the exe, types get added to the pdb relative to the 1st segment"
    )]
    address: u64,
}

// idk if this should be part of the REType, or something else
// lowkirkenuenly i should rewrite this whole program
pub fn get_pdb_type(type_name: &str, il2cpp: &Il2Cpp) -> PDBType {
    match type_name {
        "System.Boolean" => PDBType::SimpleType(SimpleTypeKind::Boolean8),
        "System.SByte" => PDBType::SimpleType(SimpleTypeKind::SByte),
        "System.Int16" => PDBType::SimpleType(SimpleTypeKind::Int16),
        "System.Int32" => PDBType::SimpleType(SimpleTypeKind::Int32),
        "System.Int64" => PDBType::SimpleType(SimpleTypeKind::Int64),
        "System.Byte" => PDBType::SimpleType(SimpleTypeKind::Byte),
        "System.UInt16" => PDBType::SimpleType(SimpleTypeKind::UInt16),
        "System.UInt32" => PDBType::SimpleType(SimpleTypeKind::UInt32),
        "System.UInt64" => PDBType::SimpleType(SimpleTypeKind::UInt64),
        "System.Single" => PDBType::SimpleType(SimpleTypeKind::Float32),
        "System.Double" => PDBType::SimpleType(SimpleTypeKind::Float64),
        "System.Char" => PDBType::SimpleType(SimpleTypeKind::WideCharacter),
        "System.Void" => PDBType::SimpleType(SimpleTypeKind::Void),
        "System.Guid" => {
            PDBType::ConstantArray(Box::new(PDBType::SimpleType(SimpleTypeKind::Byte)), 16)
        }
        _ => {
            if let Some(t) = il2cpp.get(type_name) {
                if t.parent == "System.ValueType" || t.parent == "System.Enum" {
                    return PDBType::Struct(type_name.to_string());
                }
            }
            PDBType::Pointer(Box::new(PDBType::Struct(type_name.to_string())))
        }
    }
}

// i really should impl Deserialize myself to get better descriptions of the type,
// or just convert to PDBType, etc before adding everything
#[allow(unused)]
#[derive(Debug, Deserialize)]
pub struct REType {
    #[serde(skip)]
    name: String,
    #[serde(default, deserialize_with = "parse_address_u64")]
    address: u64,
    #[serde(deserialize_with = "parse_address_u32")]
    crc: u32,
    #[serde(default, deserialize_with = "deserialize_fields")]
    fields: HashMap<String, REField>,
    #[serde(deserialize_with = "parse_address_u64")]
    fqn: u64,
    #[serde(default)]
    is_generic_type: bool,
    #[serde(default)]
    is_generic_type_definition: bool,
    #[serde(default, deserialize_with = "deserialize_methods")]
    methods: HashMap<String, REMethod>,
    #[serde(default)]
    name_hierarchy: Vec<String>,
    #[serde(default)]
    properties: HashMap<String, REProperty>,
    #[serde(deserialize_with = "parse_address_u32")]
    #[serde(default)]
    size: u32,
    #[serde(default)]
    parent: String,
}

impl REType {
    pub fn get_struct_fields(&self, il2cpp: &Il2Cpp) -> Result<Vec<StructField>> {
        let mut struct_fields = vec![];
        let not_enum_or_value =
            self.parent.as_str() != "System.Enum" && self.parent.as_str() != "System.ValueType";
        for (f_name, field) in &self.fields {
            let ty = get_pdb_type(&field.r#type, il2cpp);
            let sf = StructField {
                ty,
                name: f_name.clone(),
                offset: if not_enum_or_value {
                    field.offset_from_base as u64
                } else {
                    field.offset_from_fieldptr as u64
                },
                is_static: field.flags.contains("Static"),
            };
            struct_fields.push(sf);
        }
        struct_fields.sort_by_key(|f| f.offset);
        Ok(struct_fields)
    }

    pub fn to_pdb_type(&self) -> Result<PDBType> {
        let is_enum = self.parent == "System.Enum";
        let is_value_type = self.parent == "System.ValueType";
        //let is_array = self.parent == "System.Array";
        let t = match self.name.as_str() {
            "System.Boolean" => PDBType::SimpleType(SimpleTypeKind::Boolean8),
            "System.SByte" => PDBType::SimpleType(SimpleTypeKind::SByte),
            "System.Int16" => PDBType::SimpleType(SimpleTypeKind::Int16),
            "System.Int32" => PDBType::SimpleType(SimpleTypeKind::Int32),
            "System.Int64" => PDBType::SimpleType(SimpleTypeKind::Int64),
            "System.Byte" => PDBType::SimpleType(SimpleTypeKind::Byte),
            "System.UInt16" => PDBType::SimpleType(SimpleTypeKind::UInt16),
            "System.UInt32" => PDBType::SimpleType(SimpleTypeKind::UInt32),
            "System.UInt64" => PDBType::SimpleType(SimpleTypeKind::UInt64),
            "System.Single" => PDBType::SimpleType(SimpleTypeKind::Float32),
            "System.Double" => PDBType::SimpleType(SimpleTypeKind::Float64),
            "System.Char" => PDBType::SimpleType(SimpleTypeKind::WideCharacter),
            "System.Void" => PDBType::SimpleType(SimpleTypeKind::Void),
            "System.Guid" => {
                PDBType::ConstantArray(Box::new(PDBType::SimpleType(SimpleTypeKind::Byte)), 16)
            }
            _ => {
                if is_enum || is_value_type {
                    PDBType::Struct(self.name.to_string())
                } else {
                    PDBType::Pointer(Box::new(PDBType::Struct(self.name.to_string())))
                }
            } //_ => bail!("Unmatched type"),
        };
        Ok(t)
    }
}

#[allow(unused)]
#[derive(Debug, Deserialize)]

pub struct REField {
    #[serde(skip)]
    name: String,
    id: u32,
    init_data_index: u32,
    #[serde(deserialize_with = "parse_address_u32")]
    offset_from_base: u32,
    #[serde(deserialize_with = "parse_address_u32")]
    offset_from_fieldptr: u32,
    r#type: String,
    #[serde(default)]
    flags: String,
}

pub fn to_pdb_type(name: &str, parent: &str) -> Result<PDBType> {
    let is_enum = parent == "System.Enum";
    let is_value_type = parent == "System.ValueType";
    let t = match name {
        "System.Boolean" => PDBType::SimpleType(SimpleTypeKind::Boolean8),
        "System.SByte" => PDBType::SimpleType(SimpleTypeKind::SByte),
        "System.Int16" => PDBType::SimpleType(SimpleTypeKind::Int16),
        "System.Int32" => PDBType::SimpleType(SimpleTypeKind::Int32),
        "System.Int64" => PDBType::SimpleType(SimpleTypeKind::Int64),
        "System.Byte" => PDBType::SimpleType(SimpleTypeKind::Byte),
        "System.UInt16" => PDBType::SimpleType(SimpleTypeKind::UInt16),
        "System.UInt32" => PDBType::SimpleType(SimpleTypeKind::UInt32),
        "System.UInt64" => PDBType::SimpleType(SimpleTypeKind::UInt64),
        "System.Single" => PDBType::SimpleType(SimpleTypeKind::Float32),
        "System.Double" => PDBType::SimpleType(SimpleTypeKind::Float64),
        "System.Char" => PDBType::SimpleType(SimpleTypeKind::WideCharacter),
        "System.Void" => PDBType::SimpleType(SimpleTypeKind::Void),
        "System.Guid" => {
            PDBType::ConstantArray(Box::new(PDBType::SimpleType(SimpleTypeKind::Byte)), 8)
        }
        _ => {
            if is_enum {}
            PDBType::Pointer(Box::new(PDBType::Struct(name.to_string())))
        } //_ => bail!("Unmatched type"),
    };
    Ok(t)
}

#[allow(unused)]
#[derive(Debug, Deserialize)]
pub struct REMethod {
    #[serde(skip)]
    name: String,
    flags: Option<String>,
    #[serde(deserialize_with = "parse_address_u64")]
    function: u64,
    id: u32,
    #[serde(default)]
    impl_flags: String,
    invoke_id: u32,
    params: Option<Vec<REParam>>,
    returns: Option<REParam>,
    vtable_index: Option<u32>,
}

impl REMethod {
    pub fn symbol_name(&self, r#type: &REType) -> String {
        format!("{}::{}", r#type.name, self.name)
    }
    pub fn signature(&self, r#type: &REType) -> String {
        let params = self
            .params
            .as_ref()
            .map(|p| {
                let mut params = String::new();
                for (i, param) in p.iter().enumerate() {
                    params.push_str(&param.r#type);
                    if !param.name.is_empty() {
                        params.push(' ');

                        params.push_str(&param.name);
                    }
                    if i != p.len() {
                        params.push(',');
                    }
                }
                params
            })
            .unwrap_or("".to_string());
        let signature = format!("{}({})", self.symbol_name(r#type), params);
        signature
    }

    pub fn get_pdb_function(&self, class: Option<&str>, il2cpp: &Il2Cpp) -> PDBFunction {
        let ret_type = self
            .returns
            .as_ref()
            .and_then(|f| il2cpp.get(&f.r#type))
            .and_then(|t| t.to_pdb_type().ok())
            // this never really happens
            .unwrap_or_else(|| PDBType::SimpleType(SimpleTypeKind::Void));

        // vmctx passed in here
        let mut param_types = vec![PDBType::Pointer(Box::new(PDBType::SimpleType(
            SimpleTypeKind::Void,
        )))];

        if self.impl_flags.contains("HasThis") {
            if let Some(class_name) = class {
                param_types.push(PDBType::Pointer(Box::new(PDBType::Struct(
                    class_name.to_string(),
                ))));
            }
        }

        if let Some(params) = &self.params {
            for param in params {
                param_types.push(get_pdb_type(&param.r#type, il2cpp));
                /*let pdb_type = il2cpp
                    .get(&param.r#type)
                    .and_then(|t| t.to_pdb_type().ok())
                    .unwrap_or_else(|| PDBType::SimpleType(SimpleTypeKind::Void));
                param_types.push(pdb_type);*/
            }
        }

        let cconv = CallingConvention::NearFast;

        //let class_type = class.map(|x| PDBType::Struct(x.to_string()));
        //PDBFunction::new(ret_type, &param_types, class_type, cconv)
        PDBFunction::new_ex(ret_type, param_types, None, cconv)
    }
}

#[allow(unused)]
#[derive(Debug, Deserialize)]

pub struct REParam {
    name: String,
    r#type: String,
}

#[allow(unused)]
#[derive(Debug, Deserialize)]

pub struct REProperty {
    #[serde(skip)]
    name: String,
    getter: String,
    id: u32,
    setter: String,
}

pub type Il2Cpp = HashMap<String, REType>;

pub fn parse_address_u64<'de, D>(deserializer: D) -> Result<u64, D::Error>
where
    D: Deserializer<'de>,
{
    let s = String::deserialize(deserializer)?;
    let clean_str = s.trim_start_matches("0x");
    u64::from_str_radix(clean_str, 16).map_err(serde::de::Error::custom)
}

pub fn parse_address_u32<'de, D>(deserializer: D) -> Result<u32, D::Error>
where
    D: Deserializer<'de>,
{
    let s = String::deserialize(deserializer)?;
    let clean_str = s.trim_start_matches("0x");
    u32::from_str_radix(clean_str, 16).map_err(serde::de::Error::custom)
}

fn deserialize_fields<'de, D>(deserializer: D) -> Result<HashMap<String, REField>, D::Error>
where
    D: Deserializer<'de>,
{
    let mut map: HashMap<String, REField> = HashMap::deserialize(deserializer)?;
    for (key, t_data) in map.iter_mut() {
        t_data.name = key.clone();
    }
    Ok(map)
}

fn deserialize_methods<'de, D>(deserializer: D) -> Result<HashMap<String, REMethod>, D::Error>
where
    D: Deserializer<'de>,
{
    let mut map: HashMap<String, REMethod> = HashMap::deserialize(deserializer)?;
    for (key, t_data) in map.iter_mut() {
        t_data.name = key.clone();
    }
    Ok(map)
}

fn deserialize_il2cpp<'de, D>(deserializer: D) -> Result<Il2Cpp, D::Error>
where
    D: Deserializer<'de>,
{
    let mut map: HashMap<String, REType> = HashMap::deserialize(deserializer)?;
    for (key, t_data) in map.iter_mut() {
        t_data.name = key.clone();
    }
    Ok(map)
}

// age, signature, guid

fn get_pdb_info(args: &PdbArgs, pe: &PeFile64) -> Result<(u32, u32, [u8; 16])> {
    let mut age = 0;
    let mut guid = [0; 16];
    let mut signature = 0;
    if let Some(pdb_info) = pe.pdb_info()? {
        age = pdb_info.age();

        guid = pdb_info.guid();
    }
    if let Some(a) = args.age {
        age = a;
    }
    if let Some(g) = &args.guid {
        guid = uuid::Uuid::parse_str(&g)?.to_bytes_le();
    }
    if let Some(s) = args.signature {
        signature = s;
    }
    Ok((age, signature, guid))
}

fn add_types(pdb: &mut PDB, il2cpp: &Il2Cpp, addr_offset: u64, verbose: bool) -> Result<()> {
    for (name, t) in il2cpp {
        if name.is_empty() {
            println!("[INFO] Skipping {name:?} (empty)");
            continue;
        }
        if verbose {
            println!("Adding Type {name}");
        }

        let mut virtual_methods: Vec<&REMethod> = t
            .methods
            .values()
            .filter(|m| m.vtable_index.is_some())
            .collect();

        //let is_enum = t.parent.as_str() == "System.Enum";
        let is_value_type = t.parent.as_str() == "System.ValueType";

        if t.parent == "System.Enum" {
            //println!("Adding enum {}", t.name);
            if let Some(val_field) = t.fields.get("value__") {
                let underlying_type = il2cpp.get(&val_field.r#type);
                if let Some(underlying_ty) = underlying_type {
                    if let Ok(pdb_type) = underlying_ty.to_pdb_type() {
                        let fields = vec![StructField {
                            ty: pdb_type,
                            name: "value__".to_string(),
                            offset: 0,
                            is_static: false,
                        }];
                        pdb.insert_struct(&name, &fields, underlying_ty.size as u64)?;
                    }
                }
            }
        }
        // value types shouldnt have vtables in their structs
        // TODO: maybe i should add a boxed type with a vtable
        else if !virtual_methods.is_empty() && !is_value_type {
            // safe to unwrap here since the above filters by is_some
            virtual_methods.sort_by_key(|m| m.vtable_index.unwrap());
            let vtable_name = format!("{}__vtable", name);
            let mut vtable_fields = vec![];
            let mut max_vtable_size = 0;
            for method in &virtual_methods {
                let v_idx = method.vtable_index.unwrap() as u64;
                let pdb_func = method.get_pdb_function(Some(&name), il2cpp);
                let func_ptr_type = PDBType::Pointer(Box::new(PDBType::Function(pdb_func)));
                let offset = v_idx * 8;
                vtable_fields.push(StructField {
                    ty: func_ptr_type,
                    name: method.name.clone(),
                    offset,
                    is_static: false,
                });
                max_vtable_size = max_vtable_size.max(offset + 8);
            }
            //println!("Adding vtable {vtable_name}");
            pdb.insert_struct(&vtable_name, &vtable_fields, max_vtable_size)?;

            let mut main_struct_fields = t.get_struct_fields(il2cpp)?;
            main_struct_fields.push(StructField {
                ty: PDBType::Pointer(Box::new(PDBType::Struct(vtable_name))),
                name: "__vftable".to_string(),
                offset: 0x0,
                is_static: false,
            });
            main_struct_fields.sort_by_key(|f| f.offset);
            pdb.insert_struct(&name, &main_struct_fields, t.size as u64)?;
        } else {
            //println!("Adding normal struct {}", t.name);
            let struct_fields = t.get_struct_fields(il2cpp)?;
            pdb.insert_struct(&name, &struct_fields, t.size as u64)?;
        }

        for (_f_name, function) in &t.methods {
            if function.function != 0 {
                let signature = function.signature(t);
                if verbose {
                    println!("\tAdding function {}@{:x}", signature, function.function);
                }
                let offset_addr = (function.function - addr_offset) as u32;
                let pdb_func = function.get_pdb_function(Some(&name), il2cpp);
                let func_type = PDBType::Function(pdb_func);
                let sym_name = function.symbol_name(t);
                let mut param_names = vec![];
                param_names.push("vmctx");
                if function.impl_flags.contains("HasThis") {
                    param_names.push("this");
                }

                if let Some(params) = &function.params {
                    for param in params {
                        if param.name.is_empty() {
                            // hopefully the dissassembler renames blank names itself pls and ty
                            param_names.push("");
                        } else {
                            param_names.push(param.name.as_str());
                        }
                    }
                }
                //pdb.insert_function(1, offset_addr, &sym_name, None)?;
                pdb.insert_function(1, offset_addr, &sym_name, Some(&func_type), &param_names)?;
                //pdb.insert_function(1, offset_addr, &function.name, Some(&func_type))?;
            }
        }
    }

    Ok(())
}

fn main() -> Result<()> {
    let args = PdbArgs::parse();

    println!("[INFO] Loading il2cpp from {}", args.il2cpp);
    let il2cpp = std::fs::read_to_string(&args.il2cpp)?;
    let mut deserializer = serde_json::Deserializer::from_str(&il2cpp);
    let mut il2cpp = deserialize_il2cpp(&mut deserializer)?;

    if let Some(re) = &args.filter {
        let regex = Regex::new(&re)?;
        println!("[INFO] Filtering for \"{re}\"");
        il2cpp.retain(|k, _| regex.is_match(&k));
    }
    println!("[INFO] Finished loading il2cpp");

    println!("[INFO] Loading exe from {}", args.exe);
    let data = fs::read(&args.exe)?;
    let pe = PeFile64::parse(&*data)?;
    let is_64 = pe.is_64();
    if !is_64 {
        println!("[WARNING] exe is not 64-bit");
    }
    let (age, signature, guid) = get_pdb_info(&args, &pe)?;
    println!(
        "[INFO] age={age}, signature={signature}, guid={}",
        uuid::Uuid::from_bytes_le(guid)
    );

    let mut pdb = PDB::new(is_64, age, 0, guid).unwrap();

    let addr_offset = args.address;
    let start_time = Instant::now();
    println!("[INFO] Adding {} il2cpp types", il2cpp.len());
    add_types(&mut pdb, &il2cpp, addr_offset, args.verbose)?;
    println!(
        "[INFO] Completed in {}s",
        start_time.elapsed().as_secs_f32()
    );

    // ye idk wtf this is lol but whatever
    let exe_path = PathBuf::from(&args.exe);
    let mut output = args.output.map(|o| PathBuf::from(o)).unwrap_or_else(|| {
        exe_path
            .parent()
            .map(|x| x.to_path_buf())
            .unwrap_or(PathBuf::new())
    });
    let file_name = args.name.unwrap_or_else(|| {
        exe_path
            .file_prefix()
            .map(|x| x.to_string_lossy().to_string())
            .unwrap_or("generated".into())
    });

    let pdb_file_name = format!("{file_name}.pdb");
    output.push(pdb_file_name);
    let output = output.to_string_lossy().to_string();
    println!("[INFO] Outputting to {output}");
    pdb.commit(&args.exe, &output)?;

    Ok(())
}
