use std::{
    collections::{HashMap, HashSet},
    fs,
    path::{Path, PathBuf},
    time::Instant,
};

use anyhow::Result;
use clap::Parser;
use object::{Object, ObjectSection, read::pe::PeFile64};
use pdb_wrapper::{
    PDB, PDBEnumVariant, PDBFunction, PDBType, StructField,
    pdb_meta::{CallingConvention, SimpleTypeKind},
};
use regex::Regex;
use serde::{Deserialize, Deserializer};

#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct PdbArgs {
    #[arg(
        short,
        long,
        default_value = "il2cpp_dump.json",
        help = "path to il2cpp dump generated by reframework"
    )]
    il2cpp: String,
    #[arg(
        short,
        long,
        help = "path to the game exe, e.g 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\MonsterHunterWilds\\MonsterHunterWilds.exe'"
    )]
    exe: String,
    #[arg(
        short,
        long,
        help = "path to the output directory, e.g 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\MonsterHunterWilds'. If unspecified, it will be written to the directory of the exe"
    )]
    output: Option<String>,
    #[arg(
        short,
        long,
        help = "name of the pdb file (file will be written as \"<name>.pdb\", default uses the name of the exe)"
    )]
    name: Option<String>,
    #[arg(
        short,
        long,
        help = "override for the age that will be written to the pdb file"
    )]
    age: Option<u32>,
    #[arg(
        short,
        long,
        help = "override for the signature that will be written to the pdb file (default=0)"
    )]
    signature: Option<u32>,
    #[arg(
        short,
        long,
        help = "override for the guid that will be written to the pdb file"
    )]
    guid: Option<String>,
    #[arg(short, long, help = "regex filter for types to add")]
    filter: Option<String>,
    #[arg(
        long,
        help = "path to Enums_Internal.hpp generated by REFramework. If omitted, ree-pdb looks beside the il2cpp dump"
    )]
    enums: Option<String>,
    #[arg(
        long,
        help = "prefix enum member names with the enum type name to avoid IDA enumerator-name collisions"
    )]
    ida_safe_enums: bool,
    #[arg(short, long)]
    verbose: bool,
    #[arg(
        long,
        default_value_t = 0x140001000,
        help = "fallback base address for symbols that cannot be mapped through the PE section table"
    )]
    address: u64,
}

#[derive(Debug, Clone, Copy)]
struct PdbAddress {
    section: u16,
    offset: u32,
}

#[derive(Debug)]
struct PeSectionInfo {
    index: u16,
    address: u64,
    size: u64,
}

#[derive(Debug)]
struct AddressMap {
    sections: Vec<PeSectionInfo>,
}

impl AddressMap {
    fn from_pe(pe: &PeFile64<'_>) -> Result<Self> {
        let mut sections = Vec::new();

        for section in pe.sections() {
            let index = u16::try_from(section.index().0)
                .map_err(|_| anyhow::anyhow!("PE section index does not fit in u16"))?;
            let size = section.size();
            if size == 0 {
                continue;
            }

            sections.push(PeSectionInfo {
                index,
                address: section.address(),
                size,
            });
        }

        Ok(Self { sections })
    }

    fn resolve(&self, va: u64) -> Option<PdbAddress> {
        for section in &self.sections {
            let end = section.address.saturating_add(section.size);
            if va < section.address || va >= end {
                continue;
            }

            let offset = va - section.address;
            if offset <= u32::MAX as u64 {
                return Some(PdbAddress {
                    section: section.index,
                    offset: offset as u32,
                });
            }
        }

        None
    }
}

#[derive(Debug, Default)]
struct AddStats {
    structs_added: usize,
    enums_added: usize,
    inherited_fields_added: usize,
    functions_added: usize,
    functions_mapped_by_fallback: usize,
    functions_skipped_outside_sections: usize,
}

#[derive(Debug, Clone)]
struct EnumVariant {
    name: String,
    value: u64,
    is_unsigned: bool,
}

type EnumMap = HashMap<String, Vec<EnumVariant>>;

// idk if this should be part of the REType, or something else
// lowkirkenuenly i should rewrite this whole program
pub fn get_pdb_type(type_name: &str, il2cpp: &Il2Cpp) -> PDBType {
    match type_name {
        "System.Boolean" => PDBType::SimpleType(SimpleTypeKind::Boolean8),
        "System.SByte" => PDBType::SimpleType(SimpleTypeKind::SByte),
        "System.Int16" => PDBType::SimpleType(SimpleTypeKind::Int16),
        "System.Int32" => PDBType::SimpleType(SimpleTypeKind::Int32),
        "System.Int64" => PDBType::SimpleType(SimpleTypeKind::Int64),
        "System.Byte" => PDBType::SimpleType(SimpleTypeKind::Byte),
        "System.UInt16" => PDBType::SimpleType(SimpleTypeKind::UInt16),
        "System.UInt32" => PDBType::SimpleType(SimpleTypeKind::UInt32),
        "System.UInt64" => PDBType::SimpleType(SimpleTypeKind::UInt64),
        "System.Single" => PDBType::SimpleType(SimpleTypeKind::Float32),
        "System.Double" => PDBType::SimpleType(SimpleTypeKind::Float64),
        "System.Char" => PDBType::SimpleType(SimpleTypeKind::WideCharacter),
        "System.Void" => PDBType::SimpleType(SimpleTypeKind::Void),
        "System.Guid" => {
            PDBType::ConstantArray(Box::new(PDBType::SimpleType(SimpleTypeKind::Byte)), 16)
        }
        _ => {
            if let Some(t) = il2cpp.get(type_name) {
                if t.parent == "System.ValueType" || t.parent == "System.Enum" {
                    return PDBType::Struct(type_name.to_string());
                }
            }
            PDBType::Pointer(Box::new(PDBType::Struct(type_name.to_string())))
        }
    }
}

// i really should impl Deserialize myself to get better descriptions of the type,
// or just convert to PDBType, etc before adding everything
#[allow(unused)]
#[derive(Debug, Deserialize)]
pub struct REType {
    #[serde(skip)]
    name: String,
    #[serde(default, deserialize_with = "parse_address_u64")]
    address: u64,
    #[serde(deserialize_with = "parse_address_u32")]
    crc: u32,
    #[serde(default, deserialize_with = "deserialize_fields")]
    fields: HashMap<String, REField>,
    #[serde(deserialize_with = "parse_address_u64")]
    fqn: u64,
    #[serde(default)]
    is_generic_type: bool,
    #[serde(default)]
    is_generic_type_definition: bool,
    #[serde(default, deserialize_with = "deserialize_methods")]
    methods: HashMap<String, REMethod>,
    #[serde(default)]
    name_hierarchy: Vec<String>,
    #[serde(default)]
    properties: HashMap<String, REProperty>,
    #[serde(deserialize_with = "parse_address_u32")]
    #[serde(default)]
    size: u32,
    #[serde(default)]
    parent: String,
}

impl REType {
    fn is_enum_or_value_type(&self) -> bool {
        self.parent.as_str() == "System.Enum" || self.parent.as_str() == "System.ValueType"
    }

    fn get_field_offset(&self, field: &REField) -> u64 {
        if self.is_enum_or_value_type() {
            field.offset_from_fieldptr as u64
        } else {
            field.offset_from_base as u64
        }
    }

    fn get_own_struct_fields(
        &self,
        il2cpp: &Il2Cpp,
        inherited_name_prefix: Option<&str>,
        include_static: bool,
    ) -> Vec<StructField> {
        let mut struct_fields = vec![];
        for (f_name, field) in &self.fields {
            if !include_static && field.flags.contains("Static") {
                continue;
            }

            let ty = get_pdb_type(&field.r#type, il2cpp);
            let name = inherited_name_prefix
                .map(|prefix| format!("{prefix}__{f_name}"))
                .unwrap_or_else(|| f_name.clone());
            let sf = StructField {
                ty,
                name,
                offset: self.get_field_offset(field),
                is_static: field.flags.contains("Static"),
            };
            struct_fields.push(sf);
        }
        struct_fields
    }

    pub fn get_struct_fields(&self, il2cpp: &Il2Cpp) -> Result<(Vec<StructField>, usize)> {
        let mut struct_fields = vec![];
        let mut inherited_fields_added = 0;

        if !self.is_enum_or_value_type() {
            let mut ancestors = vec![];
            let mut parent_name = self.parent.as_str();
            let mut seen = HashSet::new();

            while !parent_name.is_empty()
                && parent_name != "System.ValueType"
                && parent_name != "System.Enum"
                && seen.insert(parent_name.to_string())
            {
                let Some(parent) = il2cpp.get(parent_name) else {
                    break;
                };
                ancestors.push(parent);
                parent_name = parent.parent.as_str();
            }

            ancestors.reverse();
            for ancestor in ancestors {
                let prefix = format!("__base_{}", sanitize_member_prefix(&ancestor.name));
                let mut fields = ancestor.get_own_struct_fields(il2cpp, Some(&prefix), false);
                inherited_fields_added += fields.len();
                struct_fields.append(&mut fields);
            }
        }

        struct_fields.append(&mut self.get_own_struct_fields(il2cpp, None, true));
        struct_fields.sort_by_key(|f| f.offset);
        Ok((struct_fields, inherited_fields_added))
    }

    pub fn to_pdb_type(&self) -> Result<PDBType> {
        let is_enum = self.parent == "System.Enum";
        let is_value_type = self.parent == "System.ValueType";
        //let is_array = self.parent == "System.Array";
        let t = match self.name.as_str() {
            "System.Boolean" => PDBType::SimpleType(SimpleTypeKind::Boolean8),
            "System.SByte" => PDBType::SimpleType(SimpleTypeKind::SByte),
            "System.Int16" => PDBType::SimpleType(SimpleTypeKind::Int16),
            "System.Int32" => PDBType::SimpleType(SimpleTypeKind::Int32),
            "System.Int64" => PDBType::SimpleType(SimpleTypeKind::Int64),
            "System.Byte" => PDBType::SimpleType(SimpleTypeKind::Byte),
            "System.UInt16" => PDBType::SimpleType(SimpleTypeKind::UInt16),
            "System.UInt32" => PDBType::SimpleType(SimpleTypeKind::UInt32),
            "System.UInt64" => PDBType::SimpleType(SimpleTypeKind::UInt64),
            "System.Single" => PDBType::SimpleType(SimpleTypeKind::Float32),
            "System.Double" => PDBType::SimpleType(SimpleTypeKind::Float64),
            "System.Char" => PDBType::SimpleType(SimpleTypeKind::WideCharacter),
            "System.Void" => PDBType::SimpleType(SimpleTypeKind::Void),
            "System.Guid" => {
                PDBType::ConstantArray(Box::new(PDBType::SimpleType(SimpleTypeKind::Byte)), 16)
            }
            _ => {
                if is_enum || is_value_type {
                    PDBType::Struct(self.name.to_string())
                } else {
                    PDBType::Pointer(Box::new(PDBType::Struct(self.name.to_string())))
                }
            } //_ => bail!("Unmatched type"),
        };
        Ok(t)
    }
}

#[allow(unused)]
#[derive(Debug, Deserialize)]

pub struct REField {
    #[serde(skip)]
    name: String,
    id: u32,
    init_data_index: u32,
    #[serde(deserialize_with = "parse_address_u32")]
    offset_from_base: u32,
    #[serde(deserialize_with = "parse_address_u32")]
    offset_from_fieldptr: u32,
    r#type: String,
    #[serde(default)]
    flags: String,
}

pub fn to_pdb_type(name: &str, parent: &str) -> Result<PDBType> {
    let is_enum = parent == "System.Enum";
    let is_value_type = parent == "System.ValueType";
    let t = match name {
        "System.Boolean" => PDBType::SimpleType(SimpleTypeKind::Boolean8),
        "System.SByte" => PDBType::SimpleType(SimpleTypeKind::SByte),
        "System.Int16" => PDBType::SimpleType(SimpleTypeKind::Int16),
        "System.Int32" => PDBType::SimpleType(SimpleTypeKind::Int32),
        "System.Int64" => PDBType::SimpleType(SimpleTypeKind::Int64),
        "System.Byte" => PDBType::SimpleType(SimpleTypeKind::Byte),
        "System.UInt16" => PDBType::SimpleType(SimpleTypeKind::UInt16),
        "System.UInt32" => PDBType::SimpleType(SimpleTypeKind::UInt32),
        "System.UInt64" => PDBType::SimpleType(SimpleTypeKind::UInt64),
        "System.Single" => PDBType::SimpleType(SimpleTypeKind::Float32),
        "System.Double" => PDBType::SimpleType(SimpleTypeKind::Float64),
        "System.Char" => PDBType::SimpleType(SimpleTypeKind::WideCharacter),
        "System.Void" => PDBType::SimpleType(SimpleTypeKind::Void),
        "System.Guid" => {
            PDBType::ConstantArray(Box::new(PDBType::SimpleType(SimpleTypeKind::Byte)), 16)
        }
        _ => {
            if is_enum || is_value_type {
                PDBType::Struct(name.to_string())
            } else {
                PDBType::Pointer(Box::new(PDBType::Struct(name.to_string())))
            }
        } //_ => bail!("Unmatched type"),
    };
    Ok(t)
}

#[allow(unused)]
#[derive(Debug, Deserialize)]
pub struct REMethod {
    #[serde(skip)]
    name: String,
    flags: Option<String>,
    #[serde(deserialize_with = "parse_address_u64")]
    function: u64,
    id: u32,
    #[serde(default)]
    impl_flags: String,
    invoke_id: u32,
    params: Option<Vec<REParam>>,
    returns: Option<REParam>,
    vtable_index: Option<u32>,
}

impl REMethod {
    pub fn symbol_name(&self, r#type: &REType) -> String {
        format!("{}::{}", r#type.name, self.name)
    }
    pub fn signature(&self, r#type: &REType) -> String {
        let params = self
            .params
            .as_ref()
            .map(|p| {
                let mut params = String::new();
                for (i, param) in p.iter().enumerate() {
                    params.push_str(&param.r#type);
                    if !param.name.is_empty() {
                        params.push(' ');

                        params.push_str(&param.name);
                    }
                    if i + 1 != p.len() {
                        params.push(',');
                    }
                }
                params
            })
            .unwrap_or("".to_string());
        let signature = format!("{}({})", self.symbol_name(r#type), params);
        signature
    }

    pub fn get_pdb_function(&self, class: Option<&str>, il2cpp: &Il2Cpp) -> PDBFunction {
        let ret_type = self
            .returns
            .as_ref()
            .and_then(|f| il2cpp.get(&f.r#type))
            .and_then(|t| t.to_pdb_type().ok())
            // this never really happens
            .unwrap_or_else(|| PDBType::SimpleType(SimpleTypeKind::Void));

        // vmctx passed in here
        let mut param_types = vec![PDBType::Pointer(Box::new(PDBType::SimpleType(
            SimpleTypeKind::Void,
        )))];

        if self.impl_flags.contains("HasThis") {
            if let Some(class_name) = class {
                param_types.push(PDBType::Pointer(Box::new(PDBType::Struct(
                    class_name.to_string(),
                ))));
            }
        }

        if let Some(params) = &self.params {
            for param in params {
                param_types.push(get_pdb_type(&param.r#type, il2cpp));
                /*let pdb_type = il2cpp
                    .get(&param.r#type)
                    .and_then(|t| t.to_pdb_type().ok())
                    .unwrap_or_else(|| PDBType::SimpleType(SimpleTypeKind::Void));
                param_types.push(pdb_type);*/
            }
        }

        let cconv = CallingConvention::NearFast;

        //let class_type = class.map(|x| PDBType::Struct(x.to_string()));
        //PDBFunction::new(ret_type, &param_types, class_type, cconv)
        PDBFunction::new_ex(ret_type, param_types, None, cconv)
    }
}

#[allow(unused)]
#[derive(Debug, Deserialize)]

pub struct REParam {
    name: String,
    r#type: String,
}

#[allow(unused)]
#[derive(Debug, Deserialize)]

pub struct REProperty {
    #[serde(skip)]
    name: String,
    getter: String,
    id: u32,
    setter: String,
}

pub type Il2Cpp = HashMap<String, REType>;

fn sanitize_member_prefix(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn parse_enum_value(raw: Option<&str>, previous_value: Option<u64>) -> Option<(u64, bool)> {
    let Some(raw) = raw else {
        return Some((
            previous_value.map(|v| v.wrapping_add(1)).unwrap_or(0),
            false,
        ));
    };

    let raw = raw.trim();
    let raw = raw.trim_end_matches(['u', 'U']);

    if let Some(hex) = raw.strip_prefix("0x").or_else(|| raw.strip_prefix("0X")) {
        let value = u64::from_str_radix(hex, 16).ok()?;
        return Some((value, value > i32::MAX as u64));
    }

    if raw.starts_with('-') {
        let value = raw.parse::<i64>().ok()?;
        return Some((value as u64, false));
    }

    let value = raw.parse::<u64>().ok()?;
    Some((value, value > i32::MAX as u64))
}

fn load_enum_map(path: &Path) -> Result<EnumMap> {
    let text = fs::read_to_string(path)?;
    let namespace_regex = Regex::new(r"namespace\s+([A-Za-z0-9_:]+)\s*\{")?;
    let enum_regex =
        Regex::new(r"enum(?:\s+class)?\s+([A-Za-z0-9_]+)(?:\s*:\s*[A-Za-z0-9_:]+)?\s*\{")?;
    let value_regex = Regex::new(r"^\s*([A-Za-z0-9_]+)\s*(?:=\s*([^,]+))?\s*,?\s*$")?;

    let lines: Vec<&str> = text.lines().collect();
    let mut enums = EnumMap::new();
    let mut namespace_stack: Vec<String> = Vec::new();
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i];

        if let Some(namespace_match) = namespace_regex.captures(line) {
            namespace_stack.push(namespace_match[1].replace("::", "."));
            i += 1;
            continue;
        }

        if line.contains('}') && !line.contains("};") && !namespace_stack.is_empty() {
            namespace_stack.pop();
            i += 1;
            continue;
        }

        if let Some(enum_match) = enum_regex.captures(line) {
            let enum_name = enum_match[1].to_string();
            let mut variants = Vec::new();
            let mut previous_value = None;

            i += 1;
            while i < lines.len() {
                let enum_line = lines[i];
                if enum_line.contains("};") || enum_line.trim() == "}" {
                    break;
                }

                if let Some(value_match) = value_regex.captures(enum_line) {
                    if let Some((value, is_unsigned)) =
                        parse_enum_value(value_match.get(2).map(|m| m.as_str()), previous_value)
                    {
                        previous_value = Some(value);
                        variants.push(EnumVariant {
                            name: value_match[1].to_string(),
                            value,
                            is_unsigned,
                        });
                    }
                }

                i += 1;
            }

            let mut type_name = namespace_stack.join(".");
            if !type_name.is_empty() {
                type_name.push('.');
            }
            type_name.push_str(&enum_name);
            enums.insert(type_name, variants);
        }

        i += 1;
    }

    Ok(enums)
}

fn resolve_enum_path(args: &PdbArgs) -> Option<PathBuf> {
    if let Some(path) = &args.enums {
        return Some(PathBuf::from(path));
    }

    let candidate = PathBuf::from(&args.il2cpp)
        .parent()
        .map(|parent| parent.join("Enums_Internal.hpp"))?;
    candidate.exists().then_some(candidate)
}

fn inheritance_depth(name: &str, il2cpp: &Il2Cpp) -> usize {
    let mut depth = 0;
    let mut current = name;
    let mut seen = HashSet::new();

    while seen.insert(current.to_string()) {
        let Some(ty) = il2cpp.get(current) else {
            break;
        };
        if ty.parent.is_empty() {
            break;
        }
        depth += 1;
        current = ty.parent.as_str();
    }

    depth
}

pub fn parse_address_u64<'de, D>(deserializer: D) -> Result<u64, D::Error>
where
    D: Deserializer<'de>,
{
    let s = String::deserialize(deserializer)?;
    let clean_str = s.trim_start_matches("0x");
    u64::from_str_radix(clean_str, 16).map_err(serde::de::Error::custom)
}

pub fn parse_address_u32<'de, D>(deserializer: D) -> Result<u32, D::Error>
where
    D: Deserializer<'de>,
{
    let s = String::deserialize(deserializer)?;
    let clean_str = s.trim_start_matches("0x");
    u32::from_str_radix(clean_str, 16).map_err(serde::de::Error::custom)
}

fn deserialize_fields<'de, D>(deserializer: D) -> Result<HashMap<String, REField>, D::Error>
where
    D: Deserializer<'de>,
{
    let mut map: HashMap<String, REField> = HashMap::deserialize(deserializer)?;
    for (key, t_data) in map.iter_mut() {
        t_data.name = key.clone();
    }
    Ok(map)
}

fn deserialize_methods<'de, D>(deserializer: D) -> Result<HashMap<String, REMethod>, D::Error>
where
    D: Deserializer<'de>,
{
    let mut map: HashMap<String, REMethod> = HashMap::deserialize(deserializer)?;
    for (key, t_data) in map.iter_mut() {
        t_data.name = key.clone();
    }
    Ok(map)
}

fn deserialize_il2cpp<'de, D>(deserializer: D) -> Result<Il2Cpp, D::Error>
where
    D: Deserializer<'de>,
{
    let mut map: HashMap<String, REType> = HashMap::deserialize(deserializer)?;
    for (key, t_data) in map.iter_mut() {
        t_data.name = key.clone();
    }
    Ok(map)
}

// age, signature, guid

fn get_pdb_info(args: &PdbArgs, pe: &PeFile64) -> Result<(u32, u32, [u8; 16])> {
    let mut age = 0;
    let mut guid = [0; 16];
    let mut signature = 0;
    if let Some(pdb_info) = pe.pdb_info()? {
        age = pdb_info.age();

        guid = pdb_info.guid();
    }
    if let Some(a) = args.age {
        age = a;
    }
    if let Some(g) = &args.guid {
        guid = uuid::Uuid::parse_str(&g)?.to_bytes_le();
    }
    if let Some(s) = args.signature {
        signature = s;
    }
    Ok((age, signature, guid))
}

fn resolve_function_address(
    address_map: &AddressMap,
    function_va: u64,
    fallback_addr_offset: u64,
) -> Option<(PdbAddress, bool)> {
    if let Some(address) = address_map.resolve(function_va) {
        return Some((address, false));
    }

    function_va
        .checked_sub(fallback_addr_offset)
        .filter(|offset| *offset <= u32::MAX as u64)
        .map(|offset| {
            (
                PdbAddress {
                    section: 1,
                    offset: offset as u32,
                },
                true,
            )
        })
}

fn add_types(
    pdb: &mut PDB,
    il2cpp: &Il2Cpp,
    enum_map: &EnumMap,
    address_map: &AddressMap,
    fallback_addr_offset: u64,
    ida_safe_enums: bool,
    verbose: bool,
) -> Result<AddStats> {
    let mut stats = AddStats::default();
    let mut type_names: Vec<&String> = il2cpp.keys().filter(|name| !name.is_empty()).collect();
    type_names.sort_by(|a, b| {
        inheritance_depth(a.as_str(), il2cpp)
            .cmp(&inheritance_depth(b.as_str(), il2cpp))
            .then_with(|| a.cmp(b))
    });

    if il2cpp.contains_key("") {
        println!("[INFO] Skipping \"\" (empty)");
    }

    for name in &type_names {
        let t = &il2cpp[*name];
        if t.parent != "System.Enum" {
            continue;
        }

        if verbose {
            println!("Adding Type {name}");
        }

        if let Some(val_field) = t.fields.get("value__") {
            let underlying_type = get_pdb_type(&val_field.r#type, il2cpp);
            if let Some(variants) = enum_map
                .get(name.as_str())
                .filter(|variants| !variants.is_empty())
            {
                let variants: Vec<PDBEnumVariant> = variants
                    .iter()
                    .map(|variant| PDBEnumVariant {
                        name: if ida_safe_enums {
                            format!(
                                "{}__{}",
                                sanitize_member_prefix(name),
                                sanitize_member_prefix(&variant.name)
                            )
                        } else {
                            variant.name.clone()
                        },
                        value: variant.value,
                        is_unsigned: variant.is_unsigned,
                    })
                    .collect();
                pdb.insert_enum(name, &underlying_type, &variants)?;
                stats.enums_added += 1;
            } else {
                let fields = vec![StructField {
                    ty: underlying_type,
                    name: "value__".to_string(),
                    offset: 0,
                    is_static: false,
                }];
                pdb.insert_struct(name, &fields, 4)?;
                stats.structs_added += 1;
            }
        }
    }

    for name in &type_names {
        let t = &il2cpp[*name];
        if t.parent == "System.Enum" {
            continue;
        }

        if verbose {
            println!("Adding Type {name}");
        }

        let mut virtual_methods: Vec<&REMethod> = t
            .methods
            .values()
            .filter(|m| m.vtable_index.is_some())
            .collect();

        let is_value_type = t.parent.as_str() == "System.ValueType";

        // value types shouldnt have vtables in their structs
        // TODO: maybe i should add a boxed type with a vtable
        if !virtual_methods.is_empty() && !is_value_type {
            // safe to unwrap here since the above filters by is_some
            virtual_methods.sort_by_key(|m| m.vtable_index.unwrap());
            let vtable_name = format!("{}__vtable", name);
            let mut vtable_fields = vec![];
            let mut max_vtable_size = 0;
            for method in &virtual_methods {
                let v_idx = method.vtable_index.unwrap() as u64;
                let pdb_func = method.get_pdb_function(Some(&name), il2cpp);
                let func_ptr_type = PDBType::Pointer(Box::new(PDBType::Function(pdb_func)));
                let offset = v_idx * 8;
                vtable_fields.push(StructField {
                    ty: func_ptr_type,
                    name: method.name.clone(),
                    offset,
                    is_static: false,
                });
                max_vtable_size = max_vtable_size.max(offset + 8);
            }
            //println!("Adding vtable {vtable_name}");
            pdb.insert_struct(&vtable_name, &vtable_fields, max_vtable_size)?;
            stats.structs_added += 1;

            let (mut main_struct_fields, inherited_fields_added) = t.get_struct_fields(il2cpp)?;
            stats.inherited_fields_added += inherited_fields_added;
            main_struct_fields.push(StructField {
                ty: PDBType::Pointer(Box::new(PDBType::Struct(vtable_name))),
                name: "__vftable".to_string(),
                offset: 0x0,
                is_static: false,
            });
            main_struct_fields.sort_by_key(|f| f.offset);
            pdb.insert_struct(&name, &main_struct_fields, t.size as u64)?;
            stats.structs_added += 1;
        } else {
            //println!("Adding normal struct {}", t.name);
            let (struct_fields, inherited_fields_added) = t.get_struct_fields(il2cpp)?;
            stats.inherited_fields_added += inherited_fields_added;
            pdb.insert_struct(&name, &struct_fields, t.size as u64)?;
            stats.structs_added += 1;
        }
    }

    for name in &type_names {
        let t = &il2cpp[*name];
        for (_f_name, function) in &t.methods {
            if function.function != 0 {
                let signature = function.signature(t);
                if verbose {
                    println!("\tAdding function {}@{:x}", signature, function.function);
                }
                let Some((pdb_address, used_fallback)) =
                    resolve_function_address(address_map, function.function, fallback_addr_offset)
                else {
                    stats.functions_skipped_outside_sections += 1;
                    if verbose {
                        println!(
                            "\tSkipping function {}@{:x}: address is outside PE sections",
                            signature, function.function
                        );
                    }
                    continue;
                };
                if used_fallback {
                    stats.functions_mapped_by_fallback += 1;
                }

                let pdb_func = function.get_pdb_function(Some(&name), il2cpp);
                let func_type = PDBType::Function(pdb_func);
                let sym_name = function.symbol_name(t);
                let mut param_names = vec![];
                param_names.push("vmctx");
                if function.impl_flags.contains("HasThis") {
                    param_names.push("this");
                }

                if let Some(params) = &function.params {
                    for param in params {
                        if param.name.is_empty() {
                            // hopefully the dissassembler renames blank names itself pls and ty
                            param_names.push("");
                        } else {
                            param_names.push(param.name.as_str());
                        }
                    }
                }
                //pdb.insert_function(1, offset_addr, &sym_name, None)?;
                pdb.insert_function(
                    pdb_address.section,
                    pdb_address.offset,
                    &sym_name,
                    Some(&func_type),
                    &param_names,
                )?;
                stats.functions_added += 1;
                //pdb.insert_function(1, offset_addr, &function.name, Some(&func_type))?;
            }
        }
    }

    Ok(stats)
}

fn main() -> Result<()> {
    let args = PdbArgs::parse();

    println!("[INFO] Loading il2cpp from {}", args.il2cpp);
    let il2cpp = std::fs::read_to_string(&args.il2cpp)?;
    let mut deserializer = serde_json::Deserializer::from_str(&il2cpp);
    let mut il2cpp = deserialize_il2cpp(&mut deserializer)?;

    if let Some(re) = &args.filter {
        let regex = Regex::new(&re)?;
        println!("[INFO] Filtering for \"{re}\"");
        il2cpp.retain(|k, _| regex.is_match(&k));
    }
    println!("[INFO] Finished loading il2cpp");

    let enum_map = if let Some(enum_path) = resolve_enum_path(&args) {
        println!("[INFO] Loading enums from {}", enum_path.display());
        let enums = load_enum_map(&enum_path)?;
        println!("[INFO] Finished loading {} enums", enums.len());
        enums
    } else {
        println!("[INFO] No Enums_Internal.hpp found; enum types will use value__ structs");
        EnumMap::new()
    };

    println!("[INFO] Loading exe from {}", args.exe);
    let data = fs::read(&args.exe)?;
    let pe = PeFile64::parse(&*data)?;
    let is_64 = pe.is_64();
    if !is_64 {
        println!("[WARNING] exe is not 64-bit");
    }
    let (age, signature, guid) = get_pdb_info(&args, &pe)?;
    println!(
        "[INFO] age={age}, signature={signature}, guid={}",
        uuid::Uuid::from_bytes_le(guid)
    );

    let mut pdb = PDB::new(is_64, age, signature, guid).unwrap();

    let address_map = AddressMap::from_pe(&pe)?;
    println!(
        "[INFO] Loaded {} PE sections for address mapping",
        address_map.sections.len()
    );
    let start_time = Instant::now();
    println!("[INFO] Adding {} il2cpp types", il2cpp.len());
    let stats = add_types(
        &mut pdb,
        &il2cpp,
        &enum_map,
        &address_map,
        args.address,
        args.ida_safe_enums,
        args.verbose,
    )?;
    println!(
        "[INFO] Added {} structs, {} enums, {} inherited fields, and {} functions in {}s",
        stats.structs_added,
        stats.enums_added,
        stats.inherited_fields_added,
        stats.functions_added,
        start_time.elapsed().as_secs_f32()
    );
    if stats.functions_mapped_by_fallback != 0 {
        println!(
            "[WARNING] Mapped {} functions with the legacy section-1 fallback",
            stats.functions_mapped_by_fallback
        );
    }
    if stats.functions_skipped_outside_sections != 0 {
        println!(
            "[WARNING] Skipped {} functions whose addresses were outside PE sections",
            stats.functions_skipped_outside_sections
        );
    }

    // ye idk wtf this is lol but whatever
    let exe_path = PathBuf::from(&args.exe);
    let mut output = args.output.map(|o| PathBuf::from(o)).unwrap_or_else(|| {
        exe_path
            .parent()
            .map(|x| x.to_path_buf())
            .unwrap_or(PathBuf::new())
    });
    let file_name = args.name.unwrap_or_else(|| {
        exe_path
            .file_prefix()
            .map(|x| x.to_string_lossy().to_string())
            .unwrap_or("generated".into())
    });

    let pdb_file_name = format!("{file_name}.pdb");
    output.push(pdb_file_name);
    let output = output.to_string_lossy().to_string();
    println!("[INFO] Outputting to {output}");
    pdb.commit(&args.exe, &output)?;

    Ok(())
}
