pub mod il2cpp;
pub mod enums;
pub mod util;
pub mod traversal;
pub mod analyzer;

use crate::enums::EnumMap;
use crate::enums::load_enum_map;
use crate::util::*;
use crate::il2cpp::*;
use crate::traversal::*;
use crate::analyzer::Analyzer;

use std::{
    collections::{HashSet},
    fs,
    path::{PathBuf},
    time::Instant,
};

use clap::Parser;
use object::{Object, ObjectSection, read::pe::PeFile64};
use pdb_wrapper::{
    PDB, PDBEnumVariant, PDBType, StructField,
    pdb_meta::{SimpleTypeKind},
};
use anyhow::Result;
use regex::Regex;

#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
pub struct PdbArgs {
    #[arg(
        short,
        long,
        default_value = "il2cpp_dump.json",
        help = "path to il2cpp dump generated by reframework"
    )]
    il2cpp: String,
    #[arg(
        short,
        long,
        help = "path to the game exe, e.g 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\MonsterHunterWilds\\MonsterHunterWilds.exe'"
    )]
    exe: String,
    #[arg(
        short,
        long,
        help = "path to the output directory, e.g 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\MonsterHunterWilds'. If unspecified, it will be written to the directory of the exe"
    )]
    output: Option<String>,
    // TODO: potentially change defaut to runtime_il2cpp.pdb, some games have that as the entry that they
    // look for instead of <GameName>.pdb
    #[arg(
        short,
        long,
        help = "name of the pdb file (file will be written as \"<name>.pdb\", default uses the name of the exe)"
    )]
    name: Option<String>,
    #[arg(
        short,
        long,
        help = "override for the age that will be written to the pdb file"
    )]
    age: Option<u32>,
    #[arg(
        short,
        long,
        help = "override for the signature that will be written to the pdb file (default=0)"
    )]
    signature: Option<u32>,
    #[arg(
        short,
        long,
        help = "override for the guid that will be written to the pdb file"
    )]
    guid: Option<String>,
    #[arg(short, long, help = "regex filter for types to add")]
    filter: Option<String>,
    #[arg(
        long,
        help = "path to Enums_Internal.hpp generated by REFramework. If omitted, ree-pdb looks beside the il2cpp dump"
    )]
    enums: Option<String>,
    #[arg(
        long,
        help = "prefix enum member names with the enum type name to avoid IDA enumerator-name collisions"
    )]
    ida_safe_enums: bool,
    #[arg(short, long)]
    verbose: bool,
    #[arg(
        long,
        default_value_t = 0x140001000,
        help = "fallback base address for symbols that cannot be mapped through the PE section table"
    )]
    address: u64,
    #[arg(long, help="Skip methods")]
    skip_methods: bool,
    #[arg(long, help="Skip types (also skips enums)")]
    skip_types: bool,
    #[arg(long, help="Skip enums")]
    skip_enums: bool,
    #[arg(long, help="Skip static field symbols")]
    skip_statics: bool,
    #[arg(short, long, help="Attempts to find thunked native functions and name add symbols for them (experimental, function args might be incorrect))")]
    resolve_native_thunks: bool,
}

pub fn resolve_enum_path(args: &PdbArgs) -> Option<PathBuf> {
    if let Some(path) = &args.enums {
        return Some(PathBuf::from(path));
    }

    let candidate = PathBuf::from(&args.il2cpp)
        .parent()
        .map(|parent| parent.join("Enums_Internal.hpp"))?;
    candidate.exists().then_some(candidate)
}

#[derive(Debug, Clone, Copy)]
struct PdbAddress {
    section: u16,
    offset: u32,
}

#[derive(Debug)]
struct PeSectionInfo {
    index: u16,
    address: u64,
    size: u64,
}

#[derive(Debug)]
struct AddressMap {
    sections: Vec<PeSectionInfo>,
}

impl AddressMap {
    fn from_pe(pe: &PeFile64<'_>) -> Result<Self> {
        let mut sections = Vec::new();

        for section in pe.sections() {
            let index = u16::try_from(section.index().0)
                .map_err(|_| anyhow::anyhow!("PE section index does not fit in u16"))?;
            let size = section.size();
            if size == 0 {
                continue;
            }

            sections.push(PeSectionInfo {
                index,
                address: section.address(),
                size,
            });
        }

        Ok(Self { sections })
    }

    fn resolve(&self, va: u64) -> Option<PdbAddress> {
        for section in &self.sections {
            let end = section.address.saturating_add(section.size);
            if va < section.address || va >= end {
                continue;
            }

            let offset = va - section.address;
            if offset <= u32::MAX as u64 {
                return Some(PdbAddress {
                    section: section.index,
                    offset: offset as u32,
                });
            }
        }

        None
    }
}

#[derive(Debug, Default)]
struct AddStats {
    structs_added: usize,
    enums_added: usize,
    inherited_fields_added: usize,
    functions_added: usize,
    functions_mapped_by_fallback: usize,
    functions_skipped_outside_sections: usize,
    thunked_functions: usize,
    native_singletons: usize,
    static_fields: usize,
}

// age, signature, guid
fn get_pdb_info(args: &PdbArgs, pe: &PeFile64) -> Result<(u32, u32, [u8; 16])> {
    let mut age = 0;
    let mut guid = [0; 16];
    let mut signature = 0;
    if let Some(pdb_info) = pe.pdb_info()? {
        age = pdb_info.age();

        guid = pdb_info.guid();
    }
    if let Some(a) = args.age {
        age = a;
    }
    if let Some(g) = &args.guid {
        guid = uuid::Uuid::parse_str(&g)?.to_bytes_le();
    }
    if let Some(s) = args.signature {
        signature = s;
    }
    Ok((age, signature, guid))
}

fn resolve_function_address(
    address_map: &AddressMap,
    function_va: u64,
    fallback_addr_offset: u64,
) -> Option<(PdbAddress, bool)> {
    if let Some(address) = address_map.resolve(function_va) {
        return Some((address, false));
    }

    function_va
        .checked_sub(fallback_addr_offset)
        .filter(|offset| *offset <= u32::MAX as u64)
        .map(|offset| {
            (
                PdbAddress {
                    section: 1,
                    offset: offset as u32,
                },
                true,
            )
        })
}

fn add_types_in_order(
    pdb: &mut PDB,
    il2cpp: &Il2Cpp,
    exe: &[u8],
    enum_map: &EnumMap,
    address_map: &AddressMap,
    filter: Option<String>,
    fallback_addr_offset: u64,
    ida_safe_enums: bool,
    skip_methods: bool,
    skip_types: bool,
    skip_enums: bool,
    skip_static: bool,
    resolve_native_thunks: bool,
    verbose: bool,
) -> Result<AddStats> {
    let mut stats = AddStats::default();
    let mut visited = HashSet::new();
    let mut symbols = HashSet::new();

    visited.insert("");
    let filter = filter.map(|s| Regex::new(&s).expect("invalid regex"));
    let added = visit_in_order(il2cpp, &mut visited, &filter, |ty| {
        let name = &ty.name;
        if !skip_types {
            if ty.is_enum() && !skip_enums {
                if verbose {
                    println!("Adding Type {name}");
                }

                if let Some(val_field) = ty.fields.get("value__") {
                    let underlying_type = get_pdb_type(&val_field.r#type, il2cpp);
                    if let Some(variants) = enum_map
                        .get(name.as_str())
                            .filter(|variants| !variants.is_empty())
                    {
                        if verbose {
                            println!("[INFO] Adding Enum {}", name);
                        }
                        let variants: Vec<PDBEnumVariant> = variants
                            .iter()
                            .map(|variant| PDBEnumVariant {
                                name: if ida_safe_enums {
                                    format!(
                                        "{}__{}",
                                        sanitize_member_prefix(name),
                                        sanitize_member_prefix(&variant.name)
                                    )
                                } else {
                                    variant.name.clone()
                                },
                                value: variant.value,
                                is_unsigned: variant.is_unsigned,
                            })
                        .collect();
                        pdb.insert_enum(name, &underlying_type, &variants).unwrap();
                        stats.enums_added += 1;
                    } else {
                        let fields = vec![StructField {
                            ty: underlying_type,
                            name: "value__".to_string(),
                            offset: 0,
                            is_static: false,
                        }];
                        pdb.insert_struct(name, &fields, 4).unwrap();
                        stats.structs_added += 1;
                    }
                }
            } else if ty.is_value_type() {
                let (struct_fields, inherited_fields_added) = ty.get_struct_fields(il2cpp).unwrap();
                stats.inherited_fields_added += inherited_fields_added;
                pdb.insert_struct(&name, &struct_fields, ty.size as u64).unwrap();
                stats.structs_added += 1;
            } else if ty.flags.contains(&RETypeFlag::ManagedVTable) && !skip_types {
                let vtable_name = format!("{}__vtable", &name);
                let (vtable_size, vtable_fields) = ty.get_struct_vtable(il2cpp).unwrap();

                if verbose {
                    println!("Adding vtable {vtable_name}");
                }
                pdb.insert_struct(&vtable_name, &vtable_fields, vtable_size).unwrap();
                stats.structs_added += 1;

                let (mut main_struct_fields, inherited_fields_added) = ty.get_struct_fields(il2cpp).unwrap();
                stats.inherited_fields_added += inherited_fields_added;
                // TODO: move this into a get_struct_fields
                if ty.parent == "System.Array" {

                    main_struct_fields.push(StructField {
                        ty: PDBType::Pointer(Box::new(PDBType::Struct(vtable_name))),
                        name: "__vftable".to_string(),
                        offset: 0x0,
                        is_static: false,
                    });
                    main_struct_fields.push(StructField {
                        ty: PDBType::SimpleType(SimpleTypeKind::UInt32),
                        name: "__ref_count".to_string(),
                        offset: 0x8,
                        is_static: false,
                    });
                    main_struct_fields.push(StructField {
                        ty: PDBType::Pointer(Box::new(PDBType::SimpleType(SimpleTypeKind::Void))),
                        name: "contained_type".to_string(),
                        offset: 0x10,
                        is_static: false,
                    });
                    main_struct_fields.push(StructField {
                        ty: PDBType::SimpleType(SimpleTypeKind::UInt32),
                        name: "count".to_string(),
                        offset: 0x18,
                        is_static: false,
                    });
                    main_struct_fields.push(StructField {
                        ty: PDBType::SimpleType(SimpleTypeKind::UInt32),
                        name: "n".to_string(),
                        offset: 0x1c,
                        is_static: false,
                    });
                    let contained_type = get_pdb_type(&array_contained_type(&ty.name), il2cpp);
                    main_struct_fields.push(StructField {
                        ty: PDBType::ConstantArray(Box::new(contained_type), 0),
                        name: "elements".to_string(),
                        offset: 0x20,
                        is_static: false,
                    });
                } else {
                    main_struct_fields.push(StructField {
                        ty: PDBType::Pointer(Box::new(PDBType::Struct(vtable_name))),
                        name: "__vftable".to_string(),
                        offset: 0x0,
                        is_static: false,
                    });
                    main_struct_fields.push(StructField {
                        ty: PDBType::SimpleType(SimpleTypeKind::UInt32),
                        name: "__ref_count".to_string(),
                        offset: 0x8,
                        is_static: false,
                    });
                }

                main_struct_fields.sort_by_key(|f| f.offset);
                if ty.parent == "System.Array" {
                    pdb.insert_struct(&name, &main_struct_fields, 0x20).unwrap();
                } else {
                    pdb.insert_struct(&name, &main_struct_fields, ty.size as u64).unwrap();
                }
                stats.structs_added += 1;
            } else {
                //println!("Adding normal struct {}", t.name);
                let (struct_fields, inherited_fields_added) = ty.get_struct_fields(il2cpp).unwrap();
                stats.inherited_fields_added += inherited_fields_added;
                pdb.insert_struct(&name, &struct_fields, ty.size as u64).unwrap();
                stats.structs_added += 1;
            }
        }


        if !skip_methods {
            for (_f_name, function) in &ty.methods {
                if function.function != 0 {
                    let signature = function.signature(ty);
                    if verbose {
                        println!("\tAdding function {}@{:x}", signature, function.function);
                    }
                    let Some((pdb_address, used_fallback)) =
                        resolve_function_address(address_map, function.function, fallback_addr_offset)
                    else {
                        stats.functions_skipped_outside_sections += 1;
                        if verbose {
                            println!(
                                "\tSkipping function {}@{:x}: address is outside PE sections",
                                signature, function.function
                            );
                        }
                        continue;
                    };
                    if used_fallback {
                        stats.functions_mapped_by_fallback += 1;
                    }

                    let pdb_func = function.get_pdb_function(Some(&name), il2cpp, true);
                    let func_type = PDBType::Function(pdb_func);
                    let sym_name = function.symbol_name(ty);
                    let mut param_names = vec![];
                    param_names.push("vmctx");
                    if function.impl_flags.contains(&REImplFlag::HasThis) {
                        param_names.push("this");
                    }

                    if let Some(params) = &function.params {
                        for param in params {
                            if param.name.is_empty() {
                                // hopefully the dissassembler renames blank names itself pls and ty
                                param_names.push("");
                            } else {
                                param_names.push(param.name.as_str());
                            }
                        }
                    }
                    //pdb.insert_function(1, offset_addr, &sym_name, None)?;
                    pdb.insert_function(
                        pdb_address.section,
                        pdb_address.offset,
                        &sym_name,
                        Some(&func_type),
                        &param_names,
                    ).unwrap();
                    stats.functions_added += 1;
                    symbols.insert(function.function);
                    //pdb.insert_function(1, offset_addr, &function.name, Some(&func_type))?;
                }
            }
        }
    });

    let analyzer = Analyzer::new(il2cpp, exe)?;
    if !skip_static {
        let native_singletons = analyzer.find_native_singletons();
        println!("[INFO] found {} native singletons", native_singletons.len());
        for (ty_name, singleton_ptr) in native_singletons {
            if added.contains(&ty_name.as_str()) {
                let Some((pdb_address, _used_fallback)) =
                    resolve_function_address(address_map, singleton_ptr, fallback_addr_offset)
                    else {
                        if verbose {
                            println!(
                                "\tSkipping singleton {}@{:x}: address is outside PE sections",
                                ty_name, singleton_ptr 
                            );
                        }
                        continue;
                    };
                    let ty = PDBType::Pointer(Box::new(PDBType::Struct(ty_name.clone())));
                    let name = format!("{ty_name}::Instance");
                    pdb.insert_global(&name, pdb_address.section, pdb_address.offset, Some(&ty))?;
                    symbols.insert(singleton_ptr);
                    stats.native_singletons += 1;
            }
        }

        let static_fields = analyzer.find_static_fields();
        println!("[INFO] found static fields for {} types", static_fields.len());
        for (ty_name, fields) in &static_fields {
            for (field_name, (addr, ret_type)) in fields {
                if added.contains(&ty_name.as_str()) {
                    let full_name = format!("{ty_name}::{field_name}");
                    let Some((pdb_address, _used_fallback)) = resolve_function_address(address_map, *addr, fallback_addr_offset) else {
                        if verbose {
                            println!(
                                "\tSkipping static field {}@{:x}: address is outside PE sections",
                                full_name, addr
                            );
                        }
                        continue;
                    };

                    // for singletons (_Instance field), the whole type name can be annoying so shorten it here
                    let name = if field_name == "_Instance" {
                        format!("{ret_type}::_Instance")
                    } else {
                        full_name
                    };
                    let ty = PDBType::Pointer(Box::new(PDBType::Struct(ret_type.clone())));
                    pdb.insert_global(&name, pdb_address.section, pdb_address.offset, Some(&ty))?;
                    symbols.insert(*addr);
                    stats.static_fields += 1;
                }
            }
        }

    }

    if resolve_native_thunks {
        let thunked = analyzer.resolve_native_thunks();
        for (ty, methods) in thunked {
            for (method, thunked_function) in methods {
                if thunked_function != 0 {
                    let signature = method.thunked_signature(ty);
                    if verbose {
                        println!("\tAdding function {}@{:x}", signature, thunked_function);
                    }
                    let Some((pdb_address, used_fallback)) =
                        resolve_function_address(address_map, thunked_function, fallback_addr_offset)
                    else {
                        stats.functions_skipped_outside_sections += 1;
                        if verbose {
                            println!(
                                "\tSkipping thunked function {}@{:x}: address is outside PE sections",
                                signature, thunked_function
                            );
                        }
                        continue;
                    };
                    if used_fallback {
                        stats.functions_mapped_by_fallback += 1;
                    }

                    let pdb_func = method.get_pdb_function(Some(&ty.name), il2cpp, false);
                    let func_type = PDBType::Function(pdb_func);
                    let sym_name = method.thunked_symbol_name(ty);
                    let mut param_names = vec![];
                    if method.impl_flags.contains(&REImplFlag::HasThis) {
                        param_names.push("this");
                    }

                    if let Some(params) = &method.params {
                        for param in params {
                            if param.name.is_empty() {
                                param_names.push("");
                            } else {
                                param_names.push(param.name.as_str());
                            }
                        }
                    }
                    pdb.insert_function(
                        pdb_address.section,
                        pdb_address.offset,
                        &sym_name,
                        Some(&func_type),
                        &param_names,
                    ).unwrap();
                    stats.thunked_functions += 1;
                    symbols.insert(method.function);
                }
            }

        }
    }

    Ok(stats)
}

fn main() -> Result<()> {
    let args = PdbArgs::parse();

    println!("[INFO] Loading il2cpp from {}", args.il2cpp);
    let il2cpp = std::fs::read_to_string(&args.il2cpp)?;
    let mut deserializer = serde_json::Deserializer::from_str(&il2cpp);
    let il2cpp = deserialize_il2cpp(&mut deserializer)?;

    println!("[INFO] Finished loading il2cpp");

    let enum_map = if let Some(enum_path) = resolve_enum_path(&args) {
        println!("[INFO] Loading enums from {}", enum_path.display());
        let enums = load_enum_map(&enum_path)?;
        println!("[INFO] Finished loading {} enums", enums.len());
        enums
    } else {
        println!("[INFO] No Enums_Internal.hpp found; enum types will use value__ structs");
        EnumMap::new()
    };

    println!("[INFO] Loading exe from {}", args.exe);
    let data = fs::read(&args.exe)?;
    let pe = PeFile64::parse(&*data)?;
    let is_64 = pe.is_64();
    if !is_64 {
        println!("[WARNING] exe is not 64-bit");
    }
    let (age, signature, guid) = get_pdb_info(&args, &pe)?;
    println!(
        "[INFO] age={age}, signature={signature}, guid={}",
        uuid::Uuid::from_bytes_le(guid)
    );

    let mut pdb = PDB::new(is_64, age, signature, guid).unwrap();

    let address_map = AddressMap::from_pe(&pe)?;
    println!(
        "[INFO] Loaded {} PE sections for address mapping",
        address_map.sections.len()
    );
    let start_time = Instant::now();

    println!("[INFO] Adding {} il2cpp types", il2cpp.len());
    // this should not have this many args lolol hahahah
    let stats = add_types_in_order(
        &mut pdb,
        &il2cpp,
        &data,
        &enum_map,
        &address_map,
        args.filter,
        args.address,
        args.ida_safe_enums,
        args.skip_methods,
        args.skip_types,
        args.skip_enums,
        args.skip_statics,
        args.resolve_native_thunks,
        args.verbose,
    )?;
    println!(
        "[INFO] Added {} structs, {} enums, {} inherited fields, {} static fields, {} native singletons, {} functions, and {} thunked_functions in {}s",
        stats.structs_added,
        stats.enums_added,
        stats.inherited_fields_added,
        stats.static_fields,
        stats.native_singletons,
        stats.functions_added,
        stats.thunked_functions,
        start_time.elapsed().as_secs_f32()
    );
    if stats.functions_mapped_by_fallback != 0 {
        println!(
            "[WARNING] Mapped {} functions with the legacy section-1 fallback",
            stats.functions_mapped_by_fallback
        );
    }
    if stats.functions_skipped_outside_sections != 0 {
        println!(
            "[WARNING] Skipped {} functions whose addresses were outside PE sections",
            stats.functions_skipped_outside_sections
        );
    }

    // ye idk wtf this is lol but whatever
    let exe_path = PathBuf::from(&args.exe);
    let mut output = args.output.map(|o| PathBuf::from(o)).unwrap_or_else(|| {
        exe_path
            .parent()
            .map(|x| x.to_path_buf())
            .unwrap_or(PathBuf::new())
    });
    let file_name = args.name.unwrap_or_else(|| {
        exe_path
            .file_prefix()
            .map(|x| x.to_string_lossy().to_string())
            .unwrap_or("generated".into())
    });

    let pdb_file_name = format!("{file_name}.pdb");
    output.push(pdb_file_name);
    let output = output.to_string_lossy().to_string();
    println!("[INFO] Outputting to {output}");
    pdb.commit(&args.exe, &output)?;

    Ok(())
}
